import { LoanPackageProvider } from '@/components/loans/loan-facility/LoanPackageContext';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Enicom Africa',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<LoanPackageProvider>{children}</LoanPackageProvider>
			</body>
		</html>
	);
}
